In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Student_performance.csv")

In [4]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66

In [5]:
df.tail()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23
9996,7,64,Yes,8,5,58
9997,6,83,Yes,8,5,74
9998,9,97,Yes,7,0,95
9999,7,74,No,8,1,64

In [6]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [7]:
df.isnull().sum() #check null before making model

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [8]:
df.dtypes # for extra currical activites we need to convert object to numeric so machine can understand it

Hours Studied                        int64
Previous Scores                      int64
Extracurricular Activities          object
Sleep Hours                          int64
Sample Question Papers Practiced     int64
Performance Index                    int64
dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [10]:
le=LabelEncoder()
le.fit_transform(df["Extracurricular Activities"])

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [11]:
df["Extracurricular Activities"]=le.fit_transform(df["Extracurricular Activities"])

In [12]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66
...,...,...,...,...,...,...
9995,1,49,1,4,2,23
9996,7,64,1,8,5,58
9997,6,83,1,8,5,74
9998,9,97,1,7,0,95
9999,7,74,0,8,1,64

In [13]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [14]:
x=df[['Hours Studied', 'Previous Scores', 'Extracurricular Activities','Sleep Hours', 'Sample Question Papers Practiced']]
y=df[['Performance Index']]

In [15]:
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [16]:
y

      Performance Index
0                    91
1                    65
2                    45
3                    36
4                    66
...                 ...
9995                 23
9996                 58
9997                 74
9998                 95
9999                 64

[10000 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [19]:
y_train

      Performance Index
9254                 36
1561                 25
1670                 59
6087                 22
6669                 40
...                 ...
5734                 48
5191                 51
5390                 44
860                  20
7270                 24

[8000 rows x 1 columns]

In [20]:
y_test

      Performance Index
6252                 51
4684                 20
1731                 46
4742                 28
4521                 41
...                 ...
6412                 45
8285                 66
7853                 16
1095                 65
6929                 47

[2000 rows x 1 columns]

In [21]:
std=StandardScaler()
X_train_std=std.fit_transform(x_train)
X_test_std=std.transform(x_test)

In [22]:
from sklearn.ensemble import RandomForestRegressor
import pickle
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [23]:
model=RandomForestRegressor()
model.fit(X_train_std,y_train)

c:\Users\Janani\anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [24]:
model.predict(X_test_std)

array([55.81  , 21.98  , 46.43  , ..., 16.09  , 63.06  , 45.2965],
      shape=(2000,))

In [25]:
y_pred=model.predict(X_test_std)

In [26]:
mean_absolute_error(y_test,y_pred)

1.813003211580087

In [27]:
mean_squared_error(y_test,y_pred)

5.152745612618947

In [28]:
r2_score(y_test,y_pred)

0.986095648772308

In [29]:
with open("student_lr_final_model.pkl",'wb') as file:
    pickle.dump((model,std,le),file)